spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mymemdb;MODE=MSSQLServer
    username: sa
    password: test
security:
  basic:
    enabled: false
  user:
    name: user
    password: password
#    data: classpath/data.sql
#    schema: classpath:schema.sql